name: Node.js CI

on:
  push:
    branches: [ develop ] #Após problemas, alterado de main para develop (23/09/2021)
  pull_request:
    branches: [ develop ] #Após problemas, alterado de main para develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install 
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}